language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install: 
  - pip install pep8
  - pip install pylint
  - pip install ipgetter
  - pip install python-nfsn
# command to run tests
script:
  - pep8 *.py
  - pylint *.py
