language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install: 
  - pip install pep8
  - pip install pylint
  - pip install ipgetter
  - pip install python-nfsn
  - pip install pyyaml
# command to run tests
script:
  - "./.travis/check_style.sh"
